### PR TITLE
Fixes #1

### LINKED ISSUE #1: Change build system from cabal to stack

### PR DESCRIPTION
**Pull request by 2016rshah**
All I really did was run `stack init` and everything worked because this project doesn't have any real dependencies or anything. Let me know if you need me to do anything else. Cheers!

### CODE REVIEW

**Comment by kc1212** [comment]
Thanks! In the README it still mentions cabal, could you update that too please?

On 5 October 2016 02:07:37 CEST, Rushi Shah notifications@github.com wrote:

> All I really did was run `stack init` and everything worked because
> this project doesn't have any real dependencies or anything. Let me
> know if you need me to do anything else. Cheers!
> You can view, comment on, or merge this pull request online at:
> 
>  https://github.com/kc1212/enigma-hs/pull/3
> 
> -- Commit Summary --
> - Fixes #1
> 
> -- File Changes --
> 
>    M .gitignore (1)
>    A stack.yaml (66)
> 
> -- Patch Links --
> 
> https://github.com/kc1212/enigma-hs/pull/3.patch
> https://github.com/kc1212/enigma-hs/pull/3.diff
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kc1212/enigma-hs/pull/3

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 2016rshah** [comment]
👍

**Comment by kc1212** [comment]
Lovely, thanks!

**Comment by kc1212** [comment]
ops, wrong button

**Pull request merged**
